# template for node apps
node_app: &node_app
  docker:
    - image: circleci/node:9.4.0-browsers
  working_directory: ~/cosmos-ui

# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  voyager:
    <<: *node_app
    environment:
      - BINARY_PATH: "/home/circleci/cosmos-ui/voyager/gaia"
      - NODE_BINARY_PATH: "/home/circleci/cosmos-ui/voyager/gaiad"

    steps:
      - checkout

      - run: cd voyager && bash ./changelog-changed-check.sh

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-root-{{ checksum "voyager/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-root-

      - run: cd voyager && yarn

      - save_cache:
          paths:
            - voyager/yarn.lock
            - voyager/node_modules
          key: v1-dependencies-root-{{ checksum "voyager/package.json" }}

      - run:
          name: Download Gaia
          command: |
            sudo wget https://www.dropbox.com/s/c82lrtttdiqtmki/gaiacli-0.16.0-linux?dl=0 -O ~/cosmos-ui/voyager/gaia
            sudo chmod o+wx ~/cosmos-ui/voyager/gaia
            sudo wget https://www.dropbox.com/s/2y0pklw9penzg87/gaiad-0.16.0-linux?dl=0 -O ~/cosmos-ui/voyager/gaiad
            sudo chmod o+wx ~/cosmos-ui/voyager/gaiad

      - run: cd voyager && yarn test
      - run: cd voyager && bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  explorer:
    <<: *node_app
    steps:
      - checkout
      - run: cd explorer && yarn
      - save_cache:
          paths:
            - explorer/yarn.lock
            - explorer/node_modules
          key: v1-dependencies-root-{{ checksum "explorer/package.json" }}
      - run: cd explorer && yarn build

workflows:
  version: 2
  build_all:
    jobs:
      - explorer
      - voyager
